# Generated by Django 5.0.4 on 2024-05-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
